#!/usr/bin/env bash

MTPROXY_PORT="${MTPROXY_PORT:-443}"
MTPROXY_STATS_PORT="${MTPROXY_STATS_PORT:-8888}"
MTPROXY_WORKERS="${MTPROXY_WORKERS:-1}"
MTPROXY_AUTO_UPDATE_TELEGRAM_FILES="${MTPROXY_AUTO_UPDATE_TELEGRAM_FILES:-1}"
MTPROXY_SECRET_FILE="${MTPROXY_SECRET_FILE:-/data/mtproxy-secret}"
MTPROXY_PUBLIC_HOST="${MTPROXY_PUBLIC_HOST:-}"
MTPROXY_NAT_PUBLIC_IP="${MTPROXY_NAT_PUBLIC_IP:-$MTPROXY_PUBLIC_HOST}"

DATA_DIR="${DATA_DIR:-/data}"
PROXY_SECRET_FILE="${PROXY_SECRET_FILE:-${DATA_DIR}/telegram-proxy-secret}"
PROXY_CONFIG_FILE="${PROXY_CONFIG_FILE:-${DATA_DIR}/telegram-proxy-config}"
